version: '3.5'
services:
  # The Application
  app:
    container_name: container_app
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: '/var/www'
    volumes:
      - ./:/var/www
    networks:
      - frontend
      - backend
    depends_on:
      - database
    environment:
      - "APP_NAME=app"
      - "APP_URL=http://localhost:8080"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_HOST=database"
      - "DB_PASSWORD=secret"

  # NGINX
  web:
    container_name: container_web
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    networks:
      - frontend
    volumes:
      - ./public:/var/www/public
    ports:
      - 8080:80
    depends_on:
      - app

  # The database
  database:
    container_name: container_db
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    networks:
      - backend
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"

  # Redis
  redis:
    container_name: container_redis
    image: redis
    ports:
      - 6379
    networks:
      - backend

networks:
  frontend:
  backend: